force-app/main/default/objects/Maintenance_Request__c/Maintenance_Request__c.object-meta.xml
<CustomObject>
    <label>Maintenance Request</label>
    <nameField>
        <label>Maintenance Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Request__c/fields/Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Date__c</fullName>
    <label>Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Confirmed</fullName>
                <default>true</default>
                <label>Not Confirmed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Last_Known_Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Last_Known_Odometer_Reading__c</fullName>
    <label>Last Known Odometer Reading</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MaintenanceReqestController_Test.cls
@isTest
private class MaintenanceReqestController_Test {
	static testMethod void MaintenanceReqestController_TestProcess(){
	}

    @TestSetup
    static void makeData(){
        List<Vehicle__c> listVehicles = new List<Vehicle__c>();

        listVehicles.add(new Vehicle__c(
            Last_Known_Odometer_Reading__c = 100,
            Name = 'Test 1'
        ));

        listVehicles.add(new Vehicle__c(
            Last_Known_Odometer_Reading__c = 10000,
            Name = 'Test 2'
        ));
        listVehicles.add(new Vehicle__c(
            Last_Known_Odometer_Reading__c = 10000,
            Name = 'Test 3'
        ));

        Database.insert(listVehicles);
    }

    @IsTest
    static void creteMaintenanceRequest_test(){
        List<Vehicle__c> listVehicles = [select Id, Last_Known_Odometer_Reading__c, name from Vehicle__c];
        // MaintenanceRequestController.creteMaintenanceRequest(listVehicles);
        
        List<Maintenance_Request__c> listMaintenanceReq = [select Id, Maintenance_Date__c, Name, Status__c from Maintenance_Request__c where Vehicle__c in :listVehicles];
        System.debug(listMaintenanceReq);
        System.assertEquals(2, listMaintenanceReq.size());
    }
}