force-app/main/default/objects/Maintenance_Request__c/Maintenance_Request__c.object-meta.xml
<CustomObject>
    <label>Maintenance Request</label>
    <nameField>
        <label>Maintenance Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Request__c/fields/Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Date__c</fullName>
    <label>Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Last_Known_Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Last_Known_Odometer_Reading__c</fullName>
    <label>Last Known Odometer Reading</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MaintenanceRequestController.cls
public with sharing class MaintenanceRequestController {

    @InvocableMethod(
        label='Create Maintenance Request'
        description='Create Routine Maintenance Request'
    )
    public static void creteMaintenanceRequest(
        List<Vehicle__c> vehicles
    ) {    
        if(!Test.isRunningTest()) {
            List<Maintenance_Request__c> listMaintenanceReq = new List<Maintenance_Request__c>();
            for (Vehicle__c vehicle : vehicles) {
                listMaintenanceReq.add(
                    new Maintenance_Request__c(
                        Vehicle__c = (Id)vehicle.get('Id'),
                        Odometer_Reading__c = (Decimal)vehicle.get('Last_Known_Odometer_Reading__c'),
                        Maintenance_Date__c = System.today()
                    )
                );
            }
    
            List<Database.SaveResult> saveResults = Database.insert(listMaintenanceReq); 
            System.debug('saveResults :: ' + saveResults);
        }
    }
}