force-app/main/default/objects/Maintenance_Part__c/Maintenance_Part__c.object-meta.xml
<CustomObject>
    <label>Maintenance Part</label>
    <nameField>
        <label>Maintenance Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Part__c/fields/Part_inventory__c.field-meta.xml
<CustomField>
    <fullName>Part_inventory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Part inventory</label>
    <referenceTo>Part_inventory__c</referenceTo>
    <relationshipLabel>Maintenance Parts</relationshipLabel>
    <relationshipName>Maintenance_Parts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance_Part__c/fields/Qty_Utilized__c.field-meta.xml
<CustomField>
    <fullName>Qty_Utilized__c</fullName>
    <label>Qty Utilized</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Part_inventory__c/Part_inventory__c.object-meta.xml
<CustomObject>
    <label>Part inventory</label>
    <nameField>
        <label>Part inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Part inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part_inventory__c/fields/Part_inventory__c.field-meta.xml
<CustomField>
    <fullName>Part_inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part inventory</label>
    <referenceTo>Part_inventory__c</referenceTo>
    <relationshipLabel>Part inventories</relationshipLabel>
    <relationshipName>Part_inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part_inventory__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Part_inventory__c/fields/Qty_In_Stock__c.field-meta.xml
<CustomField>
    <fullName>Qty_In_Stock__c</fullName>
    <label>Qty In Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MaintenancePartTriggerHandler.cls
public inherited sharing class MaintenancePartTriggerHandler extends TriggerHandler {
    private List<Maintenance_Part__c> triggerNew;
    private List<Maintenance_Part__c> triggerOld;
    private Map<Id, Maintenance_Part__c> triggerMapNew;
    private Map<Id, Maintenance_Part__c> triggerMapOld;

    @TestVisible
    private static Exception circuitBreaker;

    /**
     * @description Custom exception class
     */
    public class MaintenancePartTriggerHandlerException extends Exception {
    }

    /**
     * @description Constructor that sets class variables based on Trigger context vars
     */
    public MaintenancePartTriggerHandler() {
        this.triggerOld = (List<Maintenance_Part__c>) Trigger.old;
        this.triggerNew = (List<Maintenance_Part__c>) Trigger.new;
        this.triggerMapNew = (Map<Id, Maintenance_Part__c>) Trigger.newMap;
        this.triggerMapOld = (Map<Id, Maintenance_Part__c>) Trigger.oldMap;
    }

    /**
     * @description  : before insert context method. Called automatically by the
     *                 trigger framework this class extends
     **/
    public override void beforeInsert() {
        Map<Id, Part_inventory__c> mapPartInventory = new Map<Id, Part_inventory__c>([SELECT Id, Part_Name__c, Qty_In_Stock__c FROM Part_inventory__c]);

        for (Maintenance_Part__c mPart : this.triggerNew) {
            if(!MaintenancePartServiceLayer.validateQuantityUtilized(mapPartInventory, mapPartInventory.get((Id)mPart.get('Part_inventory__c')), Integer.valueOf(mPart.get('Qty_Utilized__c')))) {
                mPart.addError('This part is currently out of stock');
            }
        }
        // MaintenancePartServiceLayer.validateMaintenancePart(this.triggerNew);
    }

    /**
     * @description  : before update context method. Called automatically by the
     *                 trigger framework this class extends
     **/
    public override void beforeUpdate() {
        Map<Id, Part_inventory__c> mapPartInventory = new Map<Id, Part_inventory__c>([SELECT Id, Part_Name__c, Qty_In_Stock__c FROM Part_inventory__c]);

        for (Maintenance_Part__c mPart : this.triggerNew) {
            if(!MaintenancePartServiceLayer.validateQuantityUtilized(mapPartInventory, mapPartInventory.get((Id)mPart.get('Part_inventory__c')), Integer.valueOf(mPart.get('Qty_Utilized__c')))) {
                mPart.addError('This part is currently out of stock');
            }
        }
    }


    /**
     * @description  : after insert context method. Called automatically by the
     *                 trigger framework this class extends
     **/
    public override void afterInsert() {
        MaintenancePartServiceLayer.UpdatePartInventory(this.triggerNew);
    }

    /**
     * @description after update context method. Called automatically by the
     * trigger framework this class extends
     **/
    public override void afterUpdate() {

        List<Maintenance_Part__c> listMaintenanceParts = new List<Maintenance_Part__c>();

        Map<Id, Integer> mapPartsAndQuantityUtilized = new Map<Id, Integer>();
        for (Maintenance_Part__c maintenancePart : this.triggerNew) {
            mapPartsAndQuantityUtilized.put(
                (Id)maintenancePart.get('Part_inventory__c'),
                (Integer)this.triggerMapOld.get((Id)maintenancePart.get('Id')).get('Qty_Utilized__c') - (Integer)this.triggerMapNew.get((Id)maintenancePart.get('Id')).get('Qty_Utilized__c')
            );
        }

        MaintenancePartServiceLayer.UpdatePartInventory(mapPartsAndQuantityUtilized);
    }
}